.circleci/config.yml, README.md, packages/nestjs-pagination/package-lock.json, packages/nestjs-pagination/package.json
- Fix the @algoan/nestjs-pagination package version which was wrong
- Add [lerna-deploy](https://circleci.com/orbs/registry/orb/hutson/library-release-workflows#jobs-lerna-deploy) orbs in order to publish to NPM.
=> [FIX] Change Lerna publish jobs

packages/nestjs-logging-interceptor/README.md, packages/nestjs-logging-interceptor/jest.config.js, packages/nestjs-logging-interceptor/src/logging.interceptor.ts, packages/nestjs-logging-interceptor/test/logging.interceptor.test.ts
Possibility to provide the interceptor instances via an instance to set a userPrefix.
Possibility to add a userPrefix to the context message.
Readme updated.
Example:
```bash
[LoggingInterceptor - GET - /error] Incoming request - GET - /error
==>
[ExampleApp - LoggingInterceptor - GET - /error] Incoming request - GET - /error
```
Clearer context messages.
=> feat(nestjs-logging-interceptor): userPrefix in context,clearer messages

packages/nestjs-pagination/src/mongo-pagination-param.decorator.ts, packages/nestjs-pagination/test/mongo-pagination-param.test.ts
- Check if the limit is a number and set it if so (even if it is a `0` )
- Check if the page is a number and set it if so  (even if it is a `0` )
=> fix(nestjs-pagination): fetch correctly the limit and the page

package-lock.json, package.json, packages/pagination/package-lock.json
The `minimist` package got a [High Severity vulnerability](https://github.com/advisories/GHSA-vh95-rmgr-6w4m).
- Bump minimist version through the `npm audit fix` command
=> [FIX] Bump dependencies to upgrade minimist

README.md, lerna.json, package.json, packages/google-pubsub-microservice/README.md, packages/google-pubsub-microservice/jest.config.js, packages/google-pubsub-microservice/package-lock.json, packages/google-pubsub-microservice/package.json, packages/google-pubsub-microservice/src/GooglePubSubServer.ts, packages/google-pubsub-microservice/src/index.ts, packages/google-pubsub-microservice/test/GooglePubSubServer.test.ts, packages/google-pubsub-microservice/test/test-app/app.controller.ts, packages/google-pubsub-microservice/test/test-app/app.module.ts, packages/google-pubsub-microservice/test/test-app/app.service.ts, packages/google-pubsub-microservice/test/test-app/main.ts, packages/google-pubsub-microservice/tsconfig.json
Create a new package: nestjs-google-pubsub-service implementing [NestJS custom transport strategy](https://docs.nestjs.com/microservices/custom-transport)
- Create the `GCPubSubServer` class extending NestJS Server abstract class with a `listen` and a `close` method
- Add tests with a real [Google PubSub emulator](https://github.com/ert78gb/google-pubsub-emulator)
=> [FEAT] Add a new Google PubSub Microservice Package

.gitignore, packages/pagination/package.json, packages/pagination/src/index.ts, packages/pagination/src/mongo-pagination-param.decorator.ts, packages/pagination/test/add-link-header.test.ts, packages/pagination/test/helpers.ts, packages/pagination/test/mongo-pagination-param.e2e.test.ts, packages/pagination/test/mongo-pagination-param.test.ts, packages/pagination/test/mongo-pagination-param.unit.test.ts
Rewrite the MongoPaginationParamDecorator so it can be used with nest 7
BREAKING CHANGE: The new decorator works with nest 7. This do not work with nest 6
=> feat(nestjs-pagination): migrate the custom decorator to nest 7

.circleci/config.yml, README.md, package.json, packages/google-pubsub-client/README.md, packages/google-pubsub-client/jest.config.js, packages/google-pubsub-client/package-lock.json, packages/google-pubsub-client/package.json, packages/google-pubsub-client/src/GooglePubSubClient.ts, packages/google-pubsub-client/src/index.ts, packages/google-pubsub-client/test/GooglePubSubClient.test.ts, packages/google-pubsub-client/test/client-app/app.controller.ts, packages/google-pubsub-client/test/client-app/app.module.ts, packages/google-pubsub-client/test/client-app/app.service.ts, packages/google-pubsub-client/test/client-app/main.ts, packages/google-pubsub-client/test/server-app/app.controller.ts, packages/google-pubsub-client/test/server-app/app.module.ts, packages/google-pubsub-client/test/server-app/app.service.ts, packages/google-pubsub-client/test/server-app/main.ts, packages/google-pubsub-client/tsconfig.json, packages/http-exception-filter/tsconfig.json, packages/logging-interceptor/tsconfig.json, packages/pagination/tsconfig.json, packages/tsconfig.base.json
Create a new package: nestjs-google-pubsub-client implementing NestJS custom transport strategy
- Create the GCPubSubClient class extending NestJS ClientProxy abstract class with an emit method
- Add tests with the Google PubSub emulator
=> [FEAT] Add a new Google PubSub Client Package

packages/logging-interceptor/README.md, packages/logging-interceptor/src/logging.interceptor.ts, packages/logging-interceptor/test/logging.interceptor.test.ts
The defautk behavior has been changed in order to log requests and responses with the `log` level instead of the `debug` one.
- **TODO**: give to the user the ability to choose if he wants the `debug` level or not
=> [FIX] Change default log level

packages/http-exception-filter/README.md, packages/http-exception-filter/src/http-exception-filter.ts, packages/http-exception-filter/test/http-exception-filter.test.ts
Since the exception received is a subclass of the Error class, we can log the exception.stack instead of the whole exception object.
=> fix(httpexceptionfilter): logging the trace instead of the error object

packages/pagination/src/mongo-pagination-param.decorator.ts
In order to use the `filter` property, we cannot use the `{}` type. Otherwise, TS is throwing a build error:
```ts
const foo: string | undefined = pagination.filter?.foo; // Property 'foo' does not exist on type '{}'.ts(2339)
```
- fix(mongo-pagination): update the filter type to be more generic
=> [FIX] - Mongo Pagination - Change the filter interface

packages/pagination/src/add-link-header.interceptor.ts, packages/pagination/test/add-link-header.test.ts, packages/pagination/test/helpers.ts
- Return a correct result if there are no document returned by the API. Otherwise the content-range lib is returning a NaN value
=> [FIX] Pagination interceptor - Content-Range header for empty values 

packages/pagination/src/add-link-header.interceptor.ts
This fix the calculation of `rel=last` page... In the previous behavior the last page was the same "filtered" page, also I change the Math.floor to Math.ceil to properly calculate the number of pages, in the old version, in some cases we can get one extra page, for example, with 20 items and 5 items per page, the old result was 5 pages, which is wrong, with the new behavior we get exactly 4 pages :D
=> fix: fixed update last rel calculation

packages/pagination/src/add-link-header.interceptor.ts, packages/pagination/test/add-link-header.test.ts
This solve two issues:
1. When your per page limit is equal to the rows count, the link header contains a non existent next page link.
2. Last page content range is wrong, for example having 15 items, the data range is something like 0-4/15 for the first page, 5-9/15 for the second page and 10-15/15 for the last page, to be consistent the last page content range should be 10-14/15
=> feat: improved content range calculation

packages/pagination/README.md, packages/pagination/src/add-link-header.interceptor.ts, packages/pagination/src/index.ts, packages/pagination/src/mongo-pagination-param.decorator.ts, packages/pagination/test/add-link-header.test.ts, packages/pagination/test/helpers.ts
Now we can set a default limit in case the `per_page` or whatever you named, is not present in the query params.
Also a new `Pageable` interface is exported to use in your Controller responses
Some code examples:
=> feat: set default limit

packages/google-pubsub-microservice/README.md, packages/google-pubsub-microservice/src/GooglePubSubServer.ts, packages/google-pubsub-microservice/test/GooglePubSubServer.test.ts, packages/google-pubsub-microservice/test/test-app/app.controller.ts
In google-pubsub-microservice, the `GCPubSubServer` class tries to subscribe to every handler configured in the NestJS application.
Sometimes, there are more microservice handlers defined and those ones must not subscribe.
Include a configuration option `topicsNames: string[]` to be able to filter the handlers to subscribe. This option is optional, so the previous behavior is kept.
=> feat: be able to filter topic names to subscribe

packages/pagination/src/mongo-pagination-param.decorator.ts, packages/pagination/test/mongo-pagination-param.unit.test.ts
This PR aims to fix the following issue:
https://github.com/algoan/nestjs-components/issues/112
BREAKING CHANGE: 
* Modify the default value of `sort` and `project` fields in MongoPagination from `[]`
to `{}` to conform with the Mongoose documentation.
* Make those 2 fields obligatory and specify explicitly their value range
As a result, if you instantiate a `MongoPagination` object in your program without obtaining it from `@MongoPaginationParamDecorator`, you need to set fields `sort` and `project` as `{}` instead of `[]` or just omitting them
=> Change the default value of "sort" and "project" fields in MongoPagination

packages/pagination/src/mongo-pagination-param.decorator.ts, packages/pagination/test/helpers.ts, packages/pagination/test/mongo-pagination-param.e2e.test.ts, packages/pagination/test/mongo-pagination-param.unit.test.ts
This PR implements a feature which allows you to provide an array of key names in an option parameter called `exclude`  of the `@MongoPaginationParamDecorator()` decorator to filter the keys extracted from the request query.
As a result, all the keys belonging to the list will be removed from the resulting `MongoPagination` object. For example, you could use `@MongoPaginationParamDecorator( { exclude: ["$where", "$exists", accumulator] } ) pagination: MongoPagination` in the handler to exclude the corresponding fields you don't want to receive from the request query.
The principal purpose of this feature is to prevent the MongoDB injection from the client-side using Javascript code. As indicated in the MongoDB documentation, there are 4 following MongoDB operations that permit running …
=> Allow filtering the keys in the query

packages/google-pubsub-microservice/src/GooglePubSubServer.ts
Currently the default option `autoAck: true` isn't set correctly in the default parameter of the `listen()` method of GoogleCloudPubSub.
Instead, we could provide a default property `autoAck:true` in the options argument passed to the `listen()` call in the implementation of GCPubSubServer. The user can override that property by providing another value for `autoAck` in `listenOptions`.
=> Set default autoAck for listenOptions of GCPubSub

packages/google-pubsub-client/src/GooglePubSubClient.ts
> Minor tweak to prevent console spam in development mode. 
> Added options.debug test prior to logger.debug. Otherwise, irrespective of options.debug, your console gets easily flooded.
=> fix: the relentless spam if options.debug !== true

packages/pagination/src/mongo-pagination-param.decorator.ts, packages/pagination/test/mongo-pagination-param.e2e.test.ts, packages/pagination/test/mongo-pagination-param.unit.test.ts
Changing the default value for the number of results returned in the pagination to 200
=> [FIX]: Change the default limit for pagination results to 200

packages/google-pubsub-client/src/GooglePubSubClient.ts
When publishing messages sometimes is needed to add attributes to the message. The the PubSub library support to send an options parameter in the `emit` method but the NestJS emitter doesn't, so the attributes to be included in the message should be send as a part of the message.
To support adding custom attributes during emitting, a configuration option can be defined in order to remove from the message that property and to add the values as attributes.
=> feat(pubsubclient): be able to add message attributes

packages/google-pubsub-client/package-lock.json, packages/google-pubsub-client/package.json
Add support for new `@algoan/pubsub` `5.0.0` package as a peer dependency to the `@algoan/nestjs-google-pubsub-client` package.
I was trying to upgrade to use `@algoan/pubsub` `5.0.0` in a project where I use `@algoan/nestjs-google-pubsub-client@0.4.2` and ran into issues with peer dependencies.
=> fix(deps): support @algoan/pubsub 5.x.x as peer dependency

packages/pagination/src/mongo-pagination-param.decorator.ts, packages/pagination/test/mongo-pagination-param.unit.test.ts
Throw an error `Bad Request 400` if the limit/per page property is negative or zero.
Currently, if we define the limit (or per page property) as 0 or a negative number, it processes it normally.
However, this can cause some undesired behavior in the service using it:
- Dividing by zero / slicing 0 elements, hence an internal server error;
- Returning the wrong number of elements;
Also, in the link builder, a 0 limit get replaced by the default limit.
https://github.com/algoan/nestjs-components/blob/8031239295428135ca7916f6498c7d72b2eff0af/packages/pagination/src/add-link-header.interceptor.ts#L69
Finally, the 0 case can be understood as an infinite / no limit but this behavior, IMHO, is confusing and contrary with the goal of a pagination (which is to limit and stretch the request and …
=> [nestjs-pagination] Throw on invalid limit (negative or 0)

packages/google-pubsub-client/package.json, packages/google-pubsub-microservice/package.json
Allow nestjs peer dependencies to be >= 8 and @algoan/pubsub to be >= 4 for the packages:
- `google-pubsub-client`
- `google-pubsub-microservices`
This allows to update a nestjs application using those dependencies to be update to v9 or higher. Linked issue: #772
=> [FIX] Allow nestjs peer dependencies to be >= 8 and @algoan/pubsub to be >= 4

packages/logging-interceptor/README.md, packages/logging-interceptor/src/index.ts, packages/logging-interceptor/src/log.decorator.ts, packages/logging-interceptor/src/logging.interceptor.ts, packages/logging-interceptor/test/logging.interceptor.test.ts, packages/logging-interceptor/test/test-app/cats/cats.controller.ts, packages/logging-interceptor/test/test-app/cats/create-cat.dto.ts
This PR is inspired from this proposition: https://github.com/algoan/nestjs-components/pull/675
Comparing to the initial proposition, the fields to mask are not provided when the logging interceptor is built but at the method level, thanks to a Log decorator. The decorator can be used like this:
```ts
@Get('/:accountId')
@Log({ mask: { request: ['iban', 'payments.bank.name'] } })
public getAccountById(@Param('accountId') accountId: string) {
return `This action returns an account with the id ${accountId}`;
}
```
In my opinion, doing so improves the developer experience of the feature and simplify the implementation. By the way, I decided to create a generic log decorator so that we can give more logging options later on.
Please, take a look at the updated README to get details about …
=> [Logging] Add log decorator with ability to mask sensitive fields

package-lock.json, package.json, packages/logging-interceptor/package.json, packages/logging-interceptor/src/logging.interceptor.ts
Through this PR we parsed the body of the data to anonymise in the `maskData` data function to make sure that the recursive function is called on a formatted body without constructors like `new ObjectId()`
=> fix: parse the data to json before masking the properties

packages/logging-interceptor/src/logging.interceptor.ts, packages/logging-interceptor/test/logging.interceptor.test.ts, packages/logging-interceptor/test/test-app/cats/cats.controller.ts
This pull request aims to apply log masks to HTTP exception body.
For HTTP exceptions, the request body is displayed in the logs (error or warn). Thus the masking options should be applied to the body.
=> [FEAT] apply log masks to http exception body

.github/workflows/test-and-publish.yaml
Fix token used during both publish on NPM and GitHub Packages.
My previous PR #821 to add dual publish didn't work as expected.
It actually does not publish to NPM anymore. I infer this is because the NODE_AUTH_TOKEN is not uses correctly by lerna during the publish.
To fix that, we define the token and registry to use in the `.npmrc` file.
This was the method used to publish only on NPM.
=> [CI] Fix token used during both publish

README.md, package-lock.json, package.json, packages/class-transformers/README.md, packages/class-transformers/jest.config.js, packages/class-transformers/package.json, packages/class-transformers/src/enum-fallback.decorator.ts, packages/class-transformers/src/index.ts, packages/class-transformers/test/enum-fallback-decorator.test.ts, packages/class-transformers/tsconfig.json
Create class-transformers package with new decorator `EnumFallback`. This decorator can be used as follows:
```ts
import { EnumFallback } from '@algoan/nestjs-class-transformers';
export enum UserRole {
ADMIN = 'ADMIN',
READER = 'READER',
}
class User {
@EnumFallback({
type: UserRole,
fallback: (value: UserRole) => UserRole.READER // if the role is not "ADMIN" or "READER", then the role will be "READER".
})
public role?: UserRole;
}
```
Finishes implementation started in #836
Fix #834
=> [CLASS_TRANSFORMERS] Extends class-transform package with EnumFallback decorator

packages/logging-interceptor/src/logging.interceptor.ts, packages/logging-interceptor/test/logging.interceptor.test.ts
Add the following public methods to `LoggingInterceptor` class:
- `getUserPrefix`
- `getDisabledMasking`
- `getMaskingPlaceholder`
- `getMask`
Setter methods are already provided for the related fields and usually, getters should be also provided by the class. For instance, it can be useful to retrieve the masking placeholder to apply it for masking other sensitive data, not handled by this interceptor.
=> [FEAT] Add getter functions for logging interceptor fields

packages/google-pubsub-client/package.json, packages/google-pubsub-microservice/package.json
- Avoid installing the future v7 of @algoan/pubsub
With the future alpha release of [@algoan/pubsub](https://github.com/algoan/pubsub/pull/615), I wanted to make sure that it could not be installed
=> fix(deps): restrict @algoan/pubsub peer dependency

packages/http-exception-filter/src/http-exception-filter.ts, packages/http-exception-filter/test/http-exception-filter.test.ts
- Add raw error message to logs
If the HTTP error message is not logged somewhere else (e.g. with the package logging-interceptor), the error may never be logged and thus hard to debug.
This PR adds the error message returned to the client for easier debugging.
=> [http-exception-filter] Add raw error message to logs
